name: Workspace Setup
on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        shell: bash
        run: |
          .github/scripts/check_and_set-build-type.sh

      - name: Checkout AutoLM scripts
        shell: bash
        run: |
          .github/scripts/checkout-autolm-scripts.sh
