---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Workspace Setup
on:
  # Allow manually triggering the workflow
  workflow_dispatch:
    inputs:
      run_type:
        description: 'Specify the type of run'
        required: true
        default: 'manual'
  # Run on all commits that are pushed to all branches
  push:
    branches:
      - 'main'
      - 'release-*'

  # Trigger workflow on PRs to all branches
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - synchronize
      - reopened

  schedule:
    # DAILY
    - cron: '0 5 * * 1-6'

    # WEEKLY
    - cron: '0 12 * * 6'

  # Trigger workflow when enqueued to a merge group
  merge_group:

# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        shell: bash
        run: |
          .github/scripts/check_and_set-build-type.sh
      # This job uses reusable scripts for Jenkinsfile linting and artifactory ops
      # Will be replaced by Github actions equivalents
      # - name: Checkout AutoLM scripts
      #   shell: bash
      #   run: |
      #     .github/scripts/checkout-autolm-scripts.sh
